import Head from 'next/head'
import Image from 'next/image'
import 'bootstrap/dist/css/bootstrap.css'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <form className="form">
          <div className="form-group">
            <label htmlFor="compName">Company Name</label>
            <input type="text" className="form-control" id="compName" aria-describedby="nameHelp" placeholder="Enter company name"/>
          </div>
          <div className="form-group">
            <label htmlFor="jobTitle">Job title</label>
            <input type="text" className="form-control" id="jobTitle" placeholder="Enter job title"/>
          </div>
          <div className="form-group">
            <label htmlFor="dateApp">Date Applied</label>
            <input type="date" className="form-control" id="dateApp" placeholder="Enter date applied"/>
          </div>
          <button type="submit" className="btn btn-primary">Submit</button>
        </form>
      </main>
    </div>
  )
}
